import './globals.css'
import Montserrat from 'next/font/local';
const montserrat = Montserrat({
  src: '../public/Assets/fonts/Montserrat-VariableFont_wght.ttf',
  subsets: ['latin'],
  variable: '--font-montserrat',
})
export const metadata = {
  title: 'muslim-clinic',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} font-sans`}>
        {children}
      </body>
    </html>
  )
}
